### ISSUE TITLE
Can't get osc authorization

### ISSUE THREAD

**Issue by mishari** [kartaview/upload-scripts#104]
I'm getting this error

HTTPSConnectionPool(host='api.openstreetcam.org', port=443): Max retries exceeded with url: /auth/openstreetmap/client_auth (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))

Python 3.9.1
macOS 11.2.1 (20D74)

**Comment by salabogdan** [comment]
Should no longer be a problem. This was addressed a long time ago.
