### ISSUE TITLE
Uploaded GoPro image sequence is in incorrect order

### ISSUE THREAD

**Issue by karcsesz** [kartaview/upload-scripts#127]
Hello!
I have tried to upload a couple of sequences I've taken with my GoPro Hero 8 Black shooting 0.5s timelapse mode, and the resulting tracks' orderings exhibit a three steps forward, one step back pattern as can be seen on this image: ![image](https://user-images.githubusercontent.com/34425884/190174305-32fff253-dab7-4224-b42a-8a199e87503b.png)
[One of the sequences in question](https://kartaview.org/details/6091305/0/track-info)

Is it possible that the GPS Time EXIF field is rounded to whole seconds, so the images taken within the same second get swapped? I will try a 1s interval on my next trip and report back with the results.

A sample of the raw images:
[G0067200.jpg](https://user-images.githubusercontent.com/34425884/190173662-c14f005e-6236-4a53-a1bf-b17dcf9a9449.JPG)
[G0067201.jpg](https://user-images.githubusercontent.com/34425884/190173682-c0c8886f-f01f-4cc0-ac37-6773219220ed.JPG)
[G0067202.jpg](https://user-images.githubusercontent.com/34425884/190173696-5a2cedf3-c32a-43ab-8a68-9dc1c6197945.JPG)

**Comment by karcsesz** [comment]
I have uploaded [a new sequence](https://kartaview.org/details/6094025/0/track-info) with a 1s interval, and now the order seems to be good. 
![image](https://user-images.githubusercontent.com/34425884/190348920-b793138a-7fa7-4f57-8d28-906d538ca95e.png)

**Comment by salabogdan** [comment]
thanks for the contribution!
