### ISSUE TITLE
Switch to OAuth 2

### ISSUE THREAD

**Issue by danieldegroot2** [kartaview/upload-scripts#139]
Switch to OAuth 2 from HTTP Basic Auth and OAuth 1.0a. They are being deprecated.
See https://github.com/openstreetmap/operations/issues/867

cc: @GRABOSM

**Comment by trigpoint** [comment]
OAuth has now been depreciated meaning it is no longer possible to use these scripts to contribute to Kartaview.

This needs urgent attention.

**Comment by mapdevsaikat** [comment]
Hello @danieldegroot2 and @trigpoint ,

Thank you for addressing the issue. Our Engineering Team is looking into it, we will post updates here.

**Comment by davebulow** [comment]
Hello! Just wondering if there's any progress on this as I'm unable to upload anything at present.
Many thanks in advance. Looking forward to being able to use this tool to contribute more extensively to Kartaview in the near future.

**Comment by salabogdan** [comment]
[fixed by ](https://github.com/kartaview/upload-scripts/pull/142)

**Comment by davebulow** [comment]
@salabogdan Thank you so much! I just tested it and can confirm this now works. (Command line on Windows 11 in my case). Really appreciate you doing this!

**Comment by GRABOSM** [comment]
Hello @danieldegroot2 and @trigpoint,

The OAuth issue is fixed now, please feel free to give it a try. Thank you @salabogdan!

**Comment by davebulow** [comment]
@GRABOSM  Indeed, I've been testing it and the upload function is working very well! Thank you! (Hopefully the new issue where no uploads are processing will be fixed soon too. Then it'll be even better 😄. Who can I contact about it? No Kartaview uploads have been processed for the last 7 days) I've tried emailing Gab/Kartaview but heard nothing. I can't post about it here because it's unrelated to the upload scripts.

**Comment by GRABOSM** [comment]
> No Kartaview uploads have been processed for the last 7 days)

Hi @davebulow,
The issue has been resolved now, please check your previous sequence. Please try to upload new `tracks` to check, and let us know if you face any latency.
Happy contributing and Mapping!
