### ISSUE TITLE
No geotag script

### ISSUE THREAD

**Issue by seb-1204** [kartaview/upload-scripts#25]
Hi there, I recommend that OSC offers a 'endorsed' geotag photos from gpx track script. 
I would assume this could easily be forked from the [mapillary script](https://github.com/mapillary/mapillary_tools/blob/master/python/geotag_from_gpx.py) [MIT licence]

**Comment by bogdan-telenav** [comment]
So you want to upload a images but you have images  that don't contain exif but you have an gpx file for them?

**Comment by seb-1204** [comment]
That is correct. 
The workflow (for mapillary) that has proven good to me is.

1. Take pictures with GoPro and record track with Android mobile (OsmAnd+)
2. download all to computer, rough scan of images to clear out bad ones
3. apply Coordinates from gpx file to the images (using python script)
4. check image location on a map to ensure the GoPro time drift is acceptable. This has been an issue on a number of uploads where GoPro time and GPS time have drifted apart of up to 30 seconds. e.g. This results in the image from the bridge receiving a gps coordinate which is way past the bridge.
5. Upload using script.

**Comment by bogdan-telenav** [comment]
This can be done for sure. But we must invest few days in this. I will talk with the team lead and propose this to them .
Sorry for the late response. There was some issues on the flow that we improve the osm map. 
Thanks again for this advice. 👍

**Comment by bogdans-telenav** [comment]
Update on this: not quite what you requested but related to this, we now support generating exif data from OSC Metadata file format.

**Comment by salabogdan** [comment]
We now support this functionality https://github.com/kartaview/upload-scripts/pull/118
