### ISSUE TITLE
what about download-scripts?

### ISSUE THREAD

**Issue by dalacost** [kartaview/upload-scripts#35]
Hi, do you have a plan to develop a download API o something like that?

**Comment by bogdan-telenav** [comment]
Hi
Are you interested in your tracks or maybe something for personal development
Thanks.

**Comment by dalacost** [comment]
yes, I uploaded all my old photos, and i deleted it after. (many of GB), so i want to give me a opportunity to get my photos again or somebody that want it.
May If I develop a script or API we can give this alternative to users.

i did check a litte and that is not hard, getting info from "/details" and processing the Json, we can reconstruct the GPX file or set the gps position to the image again.

**Comment by alexandrui-telenav** [comment]
Hi @dalacost , the plan is to have a greatly improved 2.0 API ready in a few months that will cover the download as well. We have a few things to wrap up first, but this is high in the prio list. Something can be developed around the current API, indeed, but if it's not urgent I'd wait for the nice one.

**Comment by slumnitz** [comment]
Hello everyone, have there been any developments regarding a download API?

**Comment by vr00n** [comment]
you may want to take a look here:
https://apollo-api-v2.openstreetcam.org/apolloService/

**Comment by mds08011** [comment]
I wasn't able to open the API specification document, but there is an older PDF here: https://github.com/openstreetmap/iD/issues/4851#issuecomment-381148269

**Comment by bogdans-telenav** [comment]
@slumnitz we are still working on 2.0 API and the download will still be included there and supported in the new version of the scripts.
